version: '3'
services:
  pg:
    image: postgres:latest
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - pg-vol:/var/lib/postgresql/data
    networks:
      - pg-net
  jupyter:
    image: jupyter/datascience-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    networks:
      - pg-net

networks:
  pg-net:
