version: '3'
services:
  pg:
    image: postgres:latest
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - pg-vol:/var/lib/postgresql/data

volumes:
  pg-vol:
  
